using System;
using AutoMapper;
using SwiftCart.Application.Dto.Category;
using SwiftCart.Domain.Entities;

namespace SwiftCart.Application.Mappings;

public class CategoryMappingProfile : Profile
{
 
    public CategoryMappingProfile()
    {
     
        CreateMap<CreateCategoryDto, Category>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // ID is generated by DB
            .ForMember(dest => dest.SubCategories, opt => opt.Ignore()); // We don't create children during parent creation
          


 
        CreateMap<Category, CategoryResponseDto>()
            .MaxDepth(2); 
    }
 
}
