using System;
using AutoMapper;

namespace SwiftCart.Application.Mappings;

public class ReviewMappingProfile : Profile
{
    public ReviewMappingProfile()
    {
        CreateMap<Reviews.Dto.AddReviewDto, Domain.Entities.ProductReview>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // ID is generated by DB
            .ForMember(dest => dest.UserId, opt => opt.Ignore()) // UserId will be set in service layer
            .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()); // CreatedAt is set in service layer

        CreateMap<Domain.Entities.ProductReview, Reviews.Dto.ReviewDto>()
         .ForMember(dest => dest.Username, opt => opt.MapFrom(src => src.User.Username));  
    
}
}

